version: '3.3'
services:
  api:
    container_name: CoTalkerAPI
    restart: always 
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: CoTalker
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
